# Generated by Django 5.0.14 on 2026-07-14 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('family', models.CharField(choices=[('prospect_quality', 'Prospect quality'), ('score_confidence', 'Score confidence'), ('opportunity_score', 'Opportunity score')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('min_value', models.IntegerField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
            options={
                'ordering': ['family', '-min_value'],
            },
        ),
        migrations.CreateModel(
            name='ScoringRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('family', models.CharField(choices=[('prospect_quality', 'Prospect quality'), ('score_confidence', 'Score confidence'), ('opportunity_score', 'Opportunity score')], max_length=20)),
                ('key', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('points', models.IntegerField(default=0)),
                ('is_hard_disqualifier', models.BooleanField(default=False)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
            options={
                'ordering': ['family', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ScoreSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('family', models.CharField(choices=[('prospect_quality', 'Prospect quality'), ('score_confidence', 'Score confidence'), ('opportunity_score', 'Opportunity score')], max_length=20)),
                ('value', models.IntegerField()),
                ('is_hard_disqualified', models.BooleanField(default=False)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('components', models.JSONField(blank=True, default=list)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'family'], name='scoring_sco_content_1a3f79_idx'), models.Index(fields=['workspace'], name='scoring_sco_workspa_c6f211_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='scorethreshold',
            constraint=models.UniqueConstraint(fields=('workspace', 'family', 'label'), name='scorethreshold_unique_label_per_workspace_family'),
        ),
        migrations.AddConstraint(
            model_name='scoringrule',
            constraint=models.UniqueConstraint(fields=('workspace', 'family', 'key'), name='scoringrule_unique_key_per_workspace_family'),
        ),
    ]
