# Generated by Django 5.0.14 on 2026-07-14 21:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('provider_key', models.SlugField(max_length=100)),
                ('provider_type', models.CharField(choices=[('local_openai', 'Local OpenAI compatible'), ('cloud_openai', 'Cloud OpenAI compatible'), ('native', 'Native provider'), ('mock', 'Mock')], max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CredentialReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('encrypted_value', models.TextField()),
                ('key_version', models.PositiveSmallIntegerField(default=1)),
                ('last_rotated_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField(blank=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('requests_per_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('privacy_class', models.CharField(choices=[('local_only', 'Local only'), ('private_cloud', 'Private cloud allowed'), ('public_cloud', 'Public cloud allowed')], default='public_cloud', max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='integrations.aiprovider')),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='integrations.credentialreference')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FallbackPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('strategy', models.CharField(default='ordered', max_length=40)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ModelDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('model_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('context_limit', models.PositiveIntegerField(default=8192)),
                ('input_cost_per_million', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('output_cost_per_million', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('enabled', models.BooleanField(default=True)),
                ('capabilities', models.ManyToManyField(blank=True, related_name='models', to='integrations.modelcapability')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='integrations.aiendpoint')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ModelRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('task_type', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('required_privacy_class', models.CharField(choices=[('local_only', 'Local only'), ('private_cloud', 'Private cloud allowed'), ('public_cloud', 'Public cloud allowed')], default='public_cloud', max_length=30)),
                ('is_default', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('fallback_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.fallbackpolicy')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelRouteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.modeldefinition')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='integrations.modelroute')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='modelroute',
            name='model_definitions',
            field=models.ManyToManyField(through='integrations.ModelRouteEntry', to='integrations.modeldefinition'),
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('task_type', models.SlugField()),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField()),
                ('system_prompt', models.TextField(blank=True)),
                ('user_prompt_template', models.TextField()),
                ('output_schema', models.JSONField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='integrations.prompttemplate')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='integrations.promptversion'),
        ),
        migrations.CreateModel(
            name='ModelInvocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('task_type', models.SlugField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('estimated_cost_cents', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('output_schema_valid', models.BooleanField(null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('related_type', models.CharField(blank=True, max_length=100)),
                ('related_id', models.CharField(blank=True, max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.modeldefinition')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.modelroute')),
                ('prompt_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.promptversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderHealthCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('was_successful', models.BooleanField()),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('capabilities', models.JSONField(default=list)),
                ('sanitized_error', models.CharField(blank=True, max_length=255)),
                ('endpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.aiendpoint')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_checks', to='integrations.aiprovider')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsagePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('daily_budget_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_budget_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('max_concurrency', models.PositiveSmallIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integrations.aiprovider')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='aiprovider',
            constraint=models.UniqueConstraint(fields=('workspace', 'provider_key'), name='uniq_ai_provider_workspace_key'),
        ),
        migrations.AddConstraint(
            model_name='modelcapability',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='uniq_model_capability_workspace_key'),
        ),
        migrations.AddConstraint(
            model_name='modeldefinition',
            constraint=models.UniqueConstraint(fields=('endpoint', 'model_name'), name='uniq_endpoint_model_name'),
        ),
        migrations.AddConstraint(
            model_name='modelrouteentry',
            constraint=models.UniqueConstraint(fields=('route', 'position'), name='uniq_route_position'),
        ),
        migrations.AddConstraint(
            model_name='modelrouteentry',
            constraint=models.UniqueConstraint(fields=('route', 'model'), name='uniq_route_model'),
        ),
        migrations.AddConstraint(
            model_name='promptversion',
            constraint=models.UniqueConstraint(fields=('template', 'version'), name='uniq_prompt_template_version'),
        ),
        migrations.AddConstraint(
            model_name='prompttemplate',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='uniq_prompt_template_workspace_key'),
        ),
    ]
