# Generated by Django 5.0.14 on 2026-07-15 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0006_leadsourcehealthcheck"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadsourceconfiguration",
            name="credential",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lead_source_configurations",
                to="integrations.credentialreference",
            ),
        ),
    ]
