# Generated by Django 5.0.14 on 2026-07-14 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.UUIDField()),
                ('source_url', models.URLField(blank=True)),
                ('source_type', models.CharField(choices=[('website', 'Website'), ('job_posting', 'Job posting'), ('news', 'News'), ('social', 'Social'), ('review', 'Review'), ('manual', 'Manual'), ('other', 'Other')], max_length=20)),
                ('observed_date', models.DateField()),
                ('excerpt', models.TextField()),
                ('reliability', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('disputed', 'Disputed'), ('retracted', 'Retracted')], default='unverified', max_length=20)),
                ('is_inferred', models.BooleanField(default=False, help_text='False = directly observed claim, True = inferred/derived.')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
            options={
                'ordering': ['-observed_date'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='evidence_ev_content_7eb115_idx'), models.Index(fields=['workspace'], name='evidence_ev_workspa_2e80cb_idx')],
            },
        ),
    ]
