# Generated by Django 5.0.14 on 2026-07-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evidence", "0003_manual_claims_and_selection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evidence",
            name="source_url",
            field=models.TextField(blank=True),
        ),
    ]
