# Generated by Django 5.0.14 on 2026-07-14 18:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.CharField(choices=[('AND', 'And'), ('OR', 'Or'), ('NOT', 'Not')], max_length=3)),
                ('position', models.PositiveIntegerField(default=0, help_text='Order among sibling children; keeps clone/serialize deterministic.')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hunting.criteriongroup')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='HuntProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HuntProfileVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version_number', models.PositiveIntegerField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='hunting.huntprofile')),
                ('root_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='hunting.criteriongroup')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='huntprofile',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hunting.huntprofileversion'),
        ),
        migrations.CreateModel(
            name='ExclusionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('field', models.CharField(max_length=255)),
                ('op', models.CharField(max_length=10)),
                ('value', models.JSONField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusion_rules', to='hunting.huntprofileversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KeywordSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResultThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('min_total_score', models.IntegerField(default=0)),
                ('min_evidence_confidence', models.IntegerField(blank=True, null=True)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_threshold', to='hunting.huntprofileversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchedulePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('manual', 'Manual'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='manual', max_length=10)),
                ('is_enabled', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_policy', to='hunting.huntprofile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SearchScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('industries', models.JSONField(blank=True, default=list)),
                ('geographies', models.JSONField(blank=True, default=list)),
                ('company_size_min', models.IntegerField(blank=True, null=True)),
                ('company_size_max', models.IntegerField(blank=True, null=True)),
                ('version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_scope', to='hunting.huntprofileversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourcePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_key', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('max_records', models.IntegerField(blank=True, null=True)),
                ('budget_cents', models.IntegerField(blank=True, null=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_policies', to='hunting.huntprofileversion')),
            ],
        ),
        migrations.CreateModel(
            name='ValueSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weight', models.IntegerField(default=1)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='HuntCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('industry', 'Industry'), ('geography', 'Geography'), ('company_size', 'Company size'), ('technology', 'Technology'), ('hiring_signal', 'Hiring signal'), ('growth_signal', 'Growth signal'), ('pain_indicator', 'Pain indicator'), ('business_model', 'Business model'), ('estimated_value', 'Estimated value'), ('decision_maker_role', 'Decision-maker role'), ('keyword', 'Keyword'), ('negative_keyword', 'Negative keyword'), ('custom_attribute', 'Custom attribute')], max_length=30)),
                ('field', models.CharField(max_length=255)),
                ('op', models.CharField(max_length=10)),
                ('value', models.JSONField(blank=True, null=True)),
                ('weight', models.IntegerField(default=1)),
                ('is_required', models.BooleanField(default=False)),
                ('is_hard_disqualifier', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0, help_text='Order among sibling criteria; keeps clone/serialize deterministic.')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='hunting.criteriongroup')),
                ('keyword_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hunting.keywordset')),
                ('value_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hunting.valuesignal')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='huntprofileversion',
            constraint=models.UniqueConstraint(fields=('profile', 'version_number'), name='huntprofileversion_unique_per_profile'),
        ),
        migrations.AddConstraint(
            model_name='keywordset',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='keywordset_unique_name_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='sourcepolicy',
            constraint=models.UniqueConstraint(fields=('version', 'source_key'), name='sourcepolicy_unique_per_version'),
        ),
        migrations.AddConstraint(
            model_name='valuesignal',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='valuesignal_unique_key_per_workspace'),
        ),
    ]
