# Generated by Django 5.0.14 on 2026-07-16 23:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('evidence', '0004_alter_evidence_source_url'),
        ('finance', '0002_alter_financialtransaction_created_by'),
        ('opportunities', '0002_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(choices=[('payment', 'Payment'), ('delivery', 'Delivery'), ('relationship', 'Relationship'), ('legal_compliance', 'Legal / compliance'), ('profitability', 'Profitability'), ('strategic', 'Strategic'), ('security_privacy', 'Security / privacy'), ('founder_dependency', 'Founder dependency')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=4, default=1, max_digits=6)),
                ('stale_after_days', models.PositiveIntegerField(default=90)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ControlRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('control_type', models.CharField(choices=[('deposit', 'Deposit'), ('prepayment', 'Prepayment'), ('paid_discovery', 'Paid discovery'), ('milestone_billing', 'Milestone billing'), ('scope_limit', 'Scope limit'), ('senior_review', 'Senior review'), ('restricted_automation', 'Restricted automation'), ('rejection', 'Reject client')], max_length=30)),
                ('rationale', models.TextField()),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('implemented', 'Implemented')], default='proposed', max_length=20)),
                ('requires_approval', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risk.riskcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcceptancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=6)),
                ('control_type', models.CharField(choices=[('deposit', 'Deposit'), ('prepayment', 'Prepayment'), ('paid_discovery', 'Paid discovery'), ('milestone_billing', 'Milestone billing'), ('scope_limit', 'Scope limit'), ('senior_review', 'Senior review'), ('restricted_automation', 'Restricted automation'), ('rejection', 'Reject client')], max_length=30)),
                ('requires_approval', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risk.riskcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('rule', models.JSONField(default=dict)),
                ('weight', models.DecimalField(decimal_places=4, default=1, max_digits=6)),
                ('enabled', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='risk.riskcategory')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('acceptance_threshold', models.DecimalField(decimal_places=2, default=70, max_digits=6)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.contract')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profiles', to='organizations.organization')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='RiskObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('deterministic', 'Deterministic rule'), ('human', 'Human observation'), ('ai_suggestion', 'AI suggestion')], max_length=30)),
                ('fact_type', models.CharField(choices=[('observed', 'Observed fact'), ('inference', 'Inference'), ('override', 'Human override')], max_length=20)),
                ('source_type', models.CharField(blank=True, max_length=100)),
                ('source_id', models.CharField(blank=True, max_length=255)),
                ('explanation', models.TextField()),
                ('severity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('probability', models.DecimalField(decimal_places=2, max_digits=6)),
                ('impact', models.DecimalField(decimal_places=2, max_digits=6)),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('observed_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risk.riskcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='evidence.evidence')),
                ('factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='risk.riskfactor')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='risk.riskprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Override',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason', models.TextField()),
                ('effective_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='evidence.evidence')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risk.riskcategory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='risk.riskprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mitigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risk.controlrecommendation')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigations', to='risk.riskprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='controlrecommendation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='risk.riskprofile'),
        ),
        migrations.CreateModel(
            name='RiskSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category_scores', models.JSONField()),
                ('components', models.JSONField()),
                ('controls', models.JSONField(default=list)),
                ('calculated_at', models.DateTimeField()),
                ('calculation_version', models.CharField(max_length=50)),
                ('triggered_by', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='risk.riskprofile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('accepted', 'Accepted'), ('changes_requested', 'Changes requested')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField()),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='risk.riskprofile')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risk.risksnapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='controlrecommendation',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='risk.risksnapshot'),
        ),
        migrations.AddConstraint(
            model_name='riskcategory',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='uniq_risk_category'),
        ),
        migrations.AddConstraint(
            model_name='riskfactor',
            constraint=models.UniqueConstraint(fields=('category', 'key'), name='uniq_risk_factor'),
        ),
        migrations.AddConstraint(
            model_name='riskprofile',
            constraint=models.UniqueConstraint(fields=('organization', 'opportunity', 'contract'), name='uniq_risk_profile_scope', nulls_distinct=False),
        ),
    ]
