# Generated by Django 5.0.14 on 2026-07-14 18:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('dedupe_key', models.CharField(blank=True, max_length=255)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('workspace', 'dedupe_key'), name='organization_unique_dedupe_key_per_workspace'),
        ),
    ]
