# Generated by Django 5.0.14 on 2026-07-14 18:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('hunting', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('partial', 'Partial'), ('canceled', 'Canceled')], default='pending', max_length=10)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], max_length=10)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('checkpoint', models.JSONField(blank=True, default=dict)),
                ('error_summary', models.TextField(blank=True)),
                ('records_discovered', models.IntegerField(default=0)),
                ('records_deduplicated', models.IntegerField(default=0)),
                ('records_enriched', models.IntegerField(default=0)),
                ('records_qualified', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('cost_cents', models.IntegerField(default=0)),
                ('hunt_profile_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discovery_runs', to='hunting.huntprofileversion')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider_key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=10)),
                ('records_returned', models.IntegerField(default=0)),
                ('cost_cents', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('discovery_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_results', to='discovery.discoveryrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_key', models.CharField(max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('normalized_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('normalized', 'Normalized'), ('duplicate', 'Duplicate'), ('suppressed', 'Suppressed'), ('qualified', 'Qualified'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('failure_reason', models.TextField(blank=True)),
                ('discovery_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_records', to='discovery.discoveryrun')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrichmentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider_key', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=10)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment_runs', to='discovery.sourcerecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuppressionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('domain', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.workspace')),
            ],
        ),
        migrations.AddIndex(
            model_name='sourcerecord',
            index=models.Index(fields=['discovery_run', 'status'], name='discovery_s_discove_1e1bea_idx'),
        ),
        migrations.AddConstraint(
            model_name='suppressionentry',
            constraint=models.UniqueConstraint(fields=('workspace', 'domain'), name='suppressionentry_unique_domain_per_workspace'),
        ),
    ]
