# Generated by Django 5.0.14 on 2026-07-15 20:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("discovery", "0006_providerresult_skipped_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebPageObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("requested_url", models.TextField()),
                ("final_url", models.TextField()),
                ("canonical_url", models.TextField()),
                ("content_sha256", models.CharField(max_length=64)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                ("visible_text", models.TextField(blank=True)),
                ("contact_links", models.JSONField(blank=True, default=list)),
                ("technologies", models.JSONField(blank=True, default=list)),
                ("observed_bytes", models.PositiveIntegerField(default=0)),
                ("observed_at", models.DateTimeField()),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workspace", "created_at"], name="discovery_w_workspa_357fe8_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="webpageobservation",
            constraint=models.UniqueConstraint(
                fields=("workspace", "canonical_url", "content_sha256"),
                name="web_observation_unique_content",
            ),
        ),
    ]
